### ISSUE TITLE
Add /Verify amount of ANC-UST LP tokens, unstake, withdraw, sell ANC needed amount to repay

### ISSUE THREAD

**Issue by muellerro** [foolproof/anchor-borrow-bot#34]
Absolutely stunned by your bot! Thank you for providing the code!

**Comment by RomainLanz** [comment]
Hey @muellerro! 👋 

Could you please clarify your demands? What should `/verify` do?

**Comment by muellerro** [comment]
Hey @RomainLanz 
With /verify, the bot should check if there are any tokens available in the ANC-UST LP that can be unstaked. If yes, unstake the needed amount (= needed UST amount to repay to reach the set LTV), sell the ANC part to get UST for repaying.
For example, you need 100 UST to repay to reach the set LTV. Your ANC-UST LP value is 100 UST (30 ANC worth 60 UST plus 40 UST) or alternative check (/verify) the UST value of the staked LP, unstake, sell the ANC part and use the whole UST amount to repay.

By able to use the bot this way, you're able to provide liquidity to the ANC-UST pool (instead of deposit) and get better returns (~20% APY for deposit compared to ~45% APR for providing liquidity).

Does this make sense?

**Comment by RomainLanz** [comment]
I planned to do something similar that may fits your need, closing in the meanwhile.
