### ISSUE TITLE
Weird HTML Error

### ISSUE THREAD

**Issue by robwieser** [foolproof/anchor-borrow-bot#37]
Running on Win10.
After the bot runs about a day I receive this error message. 
It is still running but not functional,  it can be revived with the "/pause" and "/run" commands.
![2021-07-14 21_29_33-C__Windows_system32_cmd exe](https://user-images.githubusercontent.com/85581559/125681523-85500100-779d-41a8-89f9-16074ae556ec.png)

**Comment by RomainLanz** [comment]
Hey @robwieser! 👋 

This was an error returned by Cloudflare when the bot sent an HTTP request to Terra's server.
Those are displayed only for "debugging" purposes and can safely be ignored.

The bot should not have been stopped after having this error. How did you check that it was blocked?

Also, please, update to the latest release.

**Comment by robwieser** [comment]
Hi Romain,

thanks for the quick reply. 
I assumed that the bot stopped working because it didn't repay when ANC borrow reached 43% LTV.
Going to try the new version immediately.

Big thumbs up for this project. Nice work.
