### ISSUE TITLE
calculations are incorrect after the 60% increase

### ISSUE THREAD

**Issue by luigi311** [foolproof/anchor-borrow-bot#41]
Anchor just increased the limit up to 60% which is throwing the bot off. My current LTV is at 42% but the bot is reporting 35% and once that update went live the bot assumed I was at 27% and borrowed a lot more to bring me up to "35%" which I'm assuming was actually 45% though haven't really checked.

**Comment by RomainLanz** [comment]
Hey! 👋 

Should be good with `0.2.8`!

**Comment by RomainLanz** [comment]
Closing.

Waiting on few changes you proposed directly in the SDK repository to get those information differently!
